import { app, InvocationContext, Timer } from "@azure/functions";
import { getContainer } from "../shared/cosmos-client";
import { NewsClip } from "../shared/types";

const DIGEST_LOOKBACK_HOURS = 24;

function buildDigestHtml(clips: NewsClip[], generatedAt: string): string {
  if (clips.length === 0) {
    return `
      <html>
        <body>
          <h2>Governor Stein — Daily News Clips Digest</h2>
          <p><em>Generated: ${generatedAt}</em></p>
          <p>No clips found in the last ${DIGEST_LOOKBACK_HOURS} hours.</p>
        </body>
      </html>
    `;
  }

  const rows = clips
    .map(
      (clip) => `
        <tr>
          <td style="padding: 8px; border: 1px solid #ddd;">${clip.outlet}</td>
          <td style="padding: 8px; border: 1px solid #ddd;">
            <a href="${clip.url}">${clip.title}</a>
          </td>
          <td style="padding: 8px; border: 1px solid #ddd;">${clip.lede}</td>
          <td style="padding: 8px; border: 1px solid #ddd;">${clip.publishedAt}</td>
        </tr>`
    )
    .join("\n");

  return `
    <html>
      <body>
        <h2>Governor Stein — Daily News Clips Digest</h2>
        <p><em>Generated: ${generatedAt}</em></p>
        <p><strong>${clips.length} clip(s)</strong> from the last ${DIGEST_LOOKBACK_HOURS} hours.</p>
        <table style="border-collapse: collapse; width: 100%; font-family: sans-serif; font-size: 14px;">
          <thead>
            <tr style="background-color: #f2f2f2;">
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Outlet</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Title</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Lede</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Published</th>
            </tr>
          </thead>
          <tbody>
            ${rows}
          </tbody>
        </table>
        <p style="color: #666; font-size: 12px;">
          This digest is auto-generated by the NC DIT AI Office Agent.
        </p>
      </body>
    </html>
  `;
}

async function fetchRecentClips(lookbackHours: number): Promise<NewsClip[]> {
  const container = getContainer("clips");
  const cutoff = new Date(Date.now() - lookbackHours * 60 * 60 * 1000).toISOString();

  const querySpec = {
    query: "SELECT * FROM c WHERE c.publishedAt >= @cutoff ORDER BY c.publishedAt DESC",
    parameters: [{ name: "@cutoff", value: cutoff }],
  };

  const { resources } = await container.items.query<NewsClip>(querySpec).fetchAll();
  return resources;
}

async function clipsDigest(timer: Timer, context: InvocationContext): Promise<void> {
  const generatedAt = new Date().toISOString();
  context.log(`Clips digest triggered at ${generatedAt}`);

  if (timer.isPastDue) {
    context.log("Timer is past due — running anyway");
  }

  try {
    const clips = await fetchRecentClips(DIGEST_LOOKBACK_HOURS);
    context.log(`Found ${clips.length} clips in the last ${DIGEST_LOOKBACK_HOURS} hours`);

    const html = buildDigestHtml(clips, generatedAt);

    // TODO: Send digest via Logic App + Outlook connector
    // Integration approach:
    //   1. POST the HTML body to a Logic App HTTP trigger endpoint
    //   2. Logic App sends as formatted email to the comms distribution list
    //   3. Logic App endpoint URL stored in env var DIGEST_LOGIC_APP_URL
    //
    // Example:
    //   const logicAppUrl = process.env.DIGEST_LOGIC_APP_URL;
    //   if (logicAppUrl) {
    //     await fetch(logicAppUrl, {
    //       method: "POST",
    //       headers: { "Content-Type": "application/json" },
    //       body: JSON.stringify({ subject: `Daily Clips Digest — ${generatedAt.slice(0, 10)}`, html }),
    //     });
    //   }

    context.log("Digest HTML generated (email sending not yet integrated):");
    context.log(html);
  } catch (error) {
    context.error(`Clips digest failed: ${error}`);
  }
}

app.timer("clips-digest", {
  schedule: "0 0 8 * * 1-5",
  handler: clipsDigest,
});
